### ISSUE TITLE
how to set columns only max(field) without *

### ISSUE THREAD

**Issue by hawktien** [FaaPz/PDO#102]
i only want to search 'max(filed) as max' without any other fields
but the select() method set columns as * default
is this   $pdo->select(array('max(field) as max'))  the only way?

**Comment by kwhat** [comment]
Hi Tonvin,

Are you using version 1 or version 2 of the library.

**Comment by kwhat** [comment]
If you are using version 2, you can do `$pdo->select(array('max' => new Method('MAX', 'field')))`
