### ISSUE TITLE
Fix sizeof() warning

### ISSUE THREAD

**Issue by rezon73** [FaaPz/PDO#107]
$value type is not checked. It is problem when $value type is not array and not null

**Comment by dejurin** [comment]
PHP 7.2
Warning: sizeof(): Parameter must be an array or an object that implements Countable in `src/PDO/Statement/StatementContainer.php on line 514`

**Comment by kwhat** [comment]
Please begin migrating to 2.x branch.  I am not sure how many fixes are going into 1.x at this point.

**Comment by kwhat** [comment]
Is this still an issue? It looks like a fix may have been merged.

**Comment by kwhat** [comment]
I believe I just fixed this in #117.  Release shortly for 1.x
