### ISSUE TITLE
How to +1 for some field?

### ISSUE THREAD

**Issue by dxmeta** [FaaPz/PDO#108]
dateStatement = $this->getMysql()->update([$field => $field . '+' . $num])
			->table($tableName)
			->where('id', '=', $id);
		$updateStatement->execute();
Above is wrong！How to do?

**Comment by whatTool** [comment]
Hello @kotlin360 
Is this still a problem?

**Comment by kwhat** [comment]
This does not exist due to an oversight on my part.  I will see if I can come up with a good way to do this.

**Comment by kwhat** [comment]
Ok, I am merging pull request #115 that contains a Clause\Raw class to accomplish these escapes.

```
$dateStatement = $this->getMysql()->update([$field => new Raw($field . '+' . $num)])
->table($tableName)
->where('id', '=', $id);
$updateStatement->execute();
```

I am not sure if this will be the final API, but it should unblock this moving forward.
