### ISSUE TITLE
array_merge of $options in Database::__construct() loses keys.

### ISSUE THREAD

**Issue by rhys-mcguckin** [FaaPz/PDO#11]
According to http://php.net/manual/en/function.array-merge.php, the keys that are being set in https://github.com/FaaPz/Slim-PDO/blob/master/src/PDO/Database.php under the __construct function, are being renumbered, so they are being passed to the parent constructor using the incorrect values.

I'd suggest using "$options += array(default options)" statement instead, which preserves the numeric keys, while allowing what I believe is the intended behaviour here.

**Comment by FaaPz** [comment]
You're right! Just released **v1.9.2** (f557397c86ab68c379e533a7d1031858f4d88bdd) with the fix included... :grin:

**Comment by cristianp6** [comment]
Hi @FaaPz !
First of all thanks for this usefull library ;-)

Anyway, construct still loses given $options, indeed merge on [line 31](https://github.com/FaaPz/Slim-PDO/blob/master/src/PDO/Database.php#L31) should be:
`$options = $options + $this->getDefaultOptions();`
or, as suggested by rhys-mcguckin, in a shorten way
`$options += $this->getDefaultOptions();`

Am I right?
