### ISSUE TITLE
Update Testing Process

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#114]
@FaaPz,

Hope you are doing well.  I am almost done adding unit tests to the master branch.  I was wondering what service provides pull-request checks and if it would be possible to run `composer test` as part of that process?  If not, maybe Circle CI?

```
$ composer test
> phpunit --coverage-html build/coverage tests/
PHPUnit 8.2.5 by Sebastian Bergmann and contributors.

.................................SS......SSS.....SSS.....S        58 / 58 (100%)

Time: 908 ms, Memory: 8.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 58, Assertions: 67, Skipped: 9.
```
![image](https://user-images.githubusercontent.com/676164/62172663-e757ef00-b2e7-11e9-83c1-5280c3673852.png)

**Comment by FaaPz** [comment]
Hi @kwhat,

I appreciate your involvement in this project! 😄 

Currently, there’s no testing process whatsoever. The only service in use is for code styling ([StyleCI](https://styleci.io/)).

We could enable [Circle CI](https://github.com/marketplace/circleci) as you’ve mentioned, or [Travis CI](https://github.com/marketplace/travis-ci), or some other service — what’s your preference?

**Comment by kwhat** [comment]
Hey @FaaPz,

Good to hear from you!  I have no preference so I will take a look at both and pick the path of least resistance.

**Comment by kwhat** [comment]
Hey @FaaPz, 

I am going to start trying out CI with github actions.  The current CI stuff in styleci needs to be relaxed for a couple of things as they are in violation of PSR-12. This seems to mostly cover the spaces between string concat operator `.` and space after anonymous class.   Please See https://github.com/FaaPz/PDO/pull/121

**Comment by kwhat** [comment]
Also, can you enable github actions for this repo?

**Comment by FaaPz** [comment]
Hi @kwhat, I’ve just enabled GitHub Actions. ✅

**Comment by kwhat** [comment]
@FaaPz, Good deal! Looks like CI is running some linting and unit tests.  I haven't figured out a way to export the coverage report artifact yet, but the rest of it is working across Linux, OSX and Windows.  There are still those problems with the CI Style check PSR-12 conflicts I previously mentioned.  The internal linting covers must of the stuff currently in the Style CI check so up to you if you want to keep it.

**Comment by FaaPz** [comment]
@kwhat Awesome!

I’ve just disabled StyleCI for the time being. Maybe we’ll get rid of it later.
