### ISSUE TITLE
CI seems to be broken

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#126]
Hi @FaaPz,

Can you please check the CI settings for this repo.  It should be [free for public repo's](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/), however, I am seeing a "Workflows can't be executed on this repository. Please check your payment method or billing status" message.

Solution: https://github.com/ansible/community/issues/505#issuecomment-554661894

**Comment by FaaPz** [comment]
@kwhat Solved! Your suggested solution worked. 🙌
