### ISSUE TITLE
StyleCI incompatible with new PSR-12

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#127]
Hi @FaaPz,

I have gotten the builds working again, minor upstream breakage.  Any way we can loosen up the string concatenation spacing?  We appear to be in conflict with the PSR-12 standard.

https://github.styleci.io/analyses/644xaP?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by FaaPz** [comment]
StyleCI doesn't have a [PSR-12 preset](https://docs.styleci.io/presets) yet. 🤓 

We could disable StyleCI for the time being? Otherwise, it will take some time to check which [PHP fixers](https://docs.styleci.io/fixers) to use and those we shouldn't.

**Comment by kwhat** [comment]
Ha! Too bleeding edge.  We can just leave it for the time being.  All the windows and mac builds / tests are all failing right now anyway.  I will ping you again in a while ;)

**Comment by FaaPz** [comment]
I've disabled StyleCI completely for now, but their PSR-12 preset is in beta. 🙌 

- [Beta PSR-12 Support - January 03, 2020](https://blog.styleci.io/psr-12-support/)
- [New PHP Fixers - March 05, 2020](https://blog.styleci.io/new-php-fixers-3/)

**Comment by kwhat** [comment]
Nice! If want to add more restrictions, phpcs has a whole lot I've currently disabled.  Just let me know.
