### ISSUE TITLE
How to select all the records ?

### ISSUE THREAD

**Issue by ismnoiet** [FaaPz/PDO#14]
I want to fetch all the records therefore I've tried :
- without `where()`

``` php
$selectStatement = $pdo->select()
                               ->from('user')
```
- with `limit(bigNumber)`

``` php
$selectStatement = $pdo->select()
                               ->from('user')
                               ->limit(1000000);        
```

Followed by : 

``` php
$stmt = $selectStatement->execute();
        $data = $stmt->fetch(); 

        print_r($data);
```

**But i get only the first record in return**, would  you tell me what i'm missing here ? 

Thank you.

**Comment by FaaPz** [comment]
Hi @ismnoiet, you're calling `$stmt-fetch()` (aka [PDOStatement::fetch](http://php.net/manual/en/pdostatement.fetch.php)) and this method only fetches the **next row** from a result set.

Use [PDOStatement::fetchAll](http://php.net/manual/en/pdostatement.fetchall.php) instead. `$stmt->fetchAll()` returns an array containing **all of the result set rows**. :wink:

**Comment by ismnoiet** [comment]
I thought it is not a raw php PDO !, 
any way thank you very much :)
