### ISSUE TITLE
Invalid value for insert statement when trying to insert NULL

### ISSUE THREAD

**Issue by copostic** [FaaPz/PDO#144]
Hi,

I have an error when I have a NULL value on INSERT.
It just need a little modification to add is_null on Statement/Insert.php because is_scalar return false for NULL.
![image](https://user-images.githubusercontent.com/17200174/117119351-3327aa00-ad92-11eb-85a4-cb18c216da09.png)

**Comment by kwhat** [comment]
Can you provide a little more detail?  I don't understand how to reproduce this issue.

**Comment by copostic** [comment]
I programatically create the import from a JSON. When I loop, I sometime have value = NULL, to reset a value for example, so I would like to make an insert with value NULL but I have an error "Invalid value for insert statement".
When I add those two "is_null..." the problem caused by the fact that is_scalar return false for NULL is solved.

I hope I've made myself more clear, otherwise tell me :)

**Comment by Mystael** [comment]
@copostic , the issue was fixed in latest commit (2021-09-20).

**Comment by kwhat** [comment]
Should be resolved.
