### ISSUE TITLE
Creating the WHERE clause

### ISSUE THREAD

**Issue by vipers-web-design** [FaaPz/PDO#147]
I added your query builder to a folder, and installed the old school way with `require_once`, like so:
```php
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Database.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/QueryInterface.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/AbstractStatement.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/AdvancedStatement.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Statement/Insert.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Statement/Select.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Statement/Update.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Statement/Delete.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Statement/Call.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Conditional.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Grouping.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Join.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Limit.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Method.php';
require_once __DIR__ . '/../libs/backend/PDO-2.x/src/Clause/Raw.php';
```
The database connects, and I can create some basic `SELECT * FROM table ORDER BY column` queries with this library.
I'm working on cascading dropdowns, I got this Vanilla write up to work:
```sql
SELECT `id`, `name`, `country_id` FROM `states` WHERE `country_id`=? ORDER BY `name` ASC
```
When I try and rewrite that with your library, I get errors:

First write up (from: [README.md#usage](https://github.com/FaaPz/PDO#usage))
```php
$pdo->select(['`id`', '`name`', '`country_id`'])->from('`states`')->where('`country_id`', '=', $countryid)->orderBy('`name`', 'ASC');
```
I get: `Fatal error: Uncaught TypeError: Argument 1 passed to FaaPz\PDO\AdvancedStatement::where() must be an instance of FaaPz\PDO\Clause\Conditional, string given,`

My second attempt at writing (from: [SELECT.md#examples](https://github.com/FaaPz/PDO/blob/2.x/docs/Statement/SELECT.md#examples))
```php
$pdo->select(['`id`', '`name`', '`country_id`'])->from('`states`')->where(new Conditional('`country_id`', '=', $countryid))->orderBy('`name`', 'ASC');
```
The error is now: `Fatal error: Uncaught Error: Class 'Conditional' not found`

The 3rd and last example I found in the documentation (from: [CONDITIONAL.md#examples](https://github.com/FaaPz/PDO/blob/2.x/docs/Clause/CONDITIONAL.md#examples))
```php
$pdo->select(['`id`', '`name`', '`country_id`'])->from('`states`')->where(new Clause\Conditional('`country_id`', '=', $countryid))->orderBy('`name`', 'ASC');
```
The error is: `Fatal error: Uncaught Error: Class 'Clause\Conditional' not found`

**Comment by kwhat** [comment]
> First write up (from: README.md#usage)

I have update the docs for this one.

> My second attempt at writing (from: SELECT.md#examples)
> The 3rd and last example I found in the documentation (from: CONDITIONAL.md#examples)

You are missing the namespaces for both of these.  

`
use FaaPz\PDO\QueryBuilder\SQLite\Clause\Conditional;
use FaaPz\PDO\QueryBuilder\SQLite\Statement\Select;
`
