### ISSUE TITLE
Insert Many Table

### ISSUE THREAD

**Issue by ghost** [FaaPz/PDO#152]
How to insert 3 tables at once by using rollback if something fails?

**Comment by kwhat** [comment]
Same way you do with [PDO](https://www.php.net/manual/en/class.pdo.php), the [Database](https://github.com/FaaPz/PDO/blob/2.x/src/Database.php#L12) object is just an extension of PDO.

- Database[::beginTransaction()](https://www.php.net/manual/en/pdo.begintransaction.php)
- Database::[commit()](https://www.php.net/manual/en/pdo.commit.php)
- Database::[rollBack()](https://www.php.net/manual/en/pdo.rollback.php)
