### ISSUE TITLE
lastinsertid removed?

### ISSUE THREAD

**Issue by sickness0666** [FaaPz/PDO#163]
has lastInsertId() been removed?

using the new documentation and have used the: 

$insertId = $insertStatement->execute()->lastInsertId();

and get method not found

**Comment by kwhat** [comment]
Yes and the docs are incorrect, it should be:

    if ($insert->execute()) {
        $insertId = $database->lastInsertId();
    }

**Comment by kwhat** [comment]
Should be resolved in the docs.  Let me know if there are any other questions or issues.
