### ISSUE TITLE
README not up to date

### ISSUE THREAD

**Issue by copostic** [FaaPz/PDO#164]
Hello,

In the README, you mention the possibility to use insert with an associative array:
```PHP
$insert = $database->insert([
                       'id' =>1234,
                       'username' => 'user',
                       'password' => 'passwd'
                   ])
                   ->into('users');
```

But it is not possible anymore as you are using the [splat operator](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat) as you can see on the error below :

![image](https://user-images.githubusercontent.com/17200174/148243513-62f92692-2156-4d24-bcfb-73829bee2a86.png)

Is this wanted ? If true, README should be updated and documentation too, otherwise, the functionality should be fixed 

Thanks a lot,

**Comment by kwhat** [comment]
I just updated 2.x.  Let me know if you find any other issues.

**Comment by copostic** [comment]
> I just updated 2.x. Let me know if you find any other issues.

I will !
In fact, I am, in the README the list of columns should be surrounded by brackets as columns method only accept one argument. Or is the doc about Insert is not up to date either ? [Insert.md](https://github.com/FaaPz/PDO/blob/2.x/docs/Statement/Insert.md)
So you confirm that it's a decision to remove to possibility to use key-value array for insert ?

Thanks for your help anyway 😄

**Comment by kwhat** [comment]
It takes a column array without values because it now supports multiple calls to ->values().  This probably wasn't the best decision on my part.

**Comment by copostic** [comment]
> It takes a column array without values because it now supports multiple calls to ->values(). This probably wasn't the best decision on my part.

Wouldn't it have been better to use overload methods ? Or even just keep the array key/value method with another name and that would reproduce behaviour of ->columns()->values() ?
