### ISSUE TITLE
orderBy is not rendered when optional direction is omitted

### ISSUE THREAD

**Issue by jerome2710** [FaaPz/PDO#165]
Please correct me if I'm wrong, but I think the `->orderBy()` direction isn't optional. While [the second argument is not required](https://github.com/FaaPz/PDO/blob/2.x/src/AdvancedStatement.php#L85), [the rendering checks the value](https://github.com/FaaPz/PDO/blob/2.x/src/AdvancedStatement.php#L98) and will continue if there is none.

`->orderBy('RAND()')` or `->orderBy('id')` are currently being discarded when the SQL is rendered.

**Comment by kwhat** [comment]
Should be an easy fix:

`if (($direction = reset($this->orderBy)) !== false) {`

**Comment by kwhat** [comment]
Should be resolved.
