### ISSUE TITLE
MsSQL Limit Clause

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#18]
I don't have a suggestion for this one yet, but if something dawns on me, I'll create a pull request.  So the select limit clause needs a check for MS SQL as it use a differen `SELECT TOP n * FROM table;` notation.

**Comment by kwhat** [comment]
Nice work on this library.  It's one of the best standalone query builders I have seen on packagist.  This issue should be fairly simple to fix in short term.  If most of the private members and functions in SelectStatement were changed to protected, I could extended it and override getSelect() to implement the MsSQL limit.  The same sort of thing will probably apply to other classes.  The long term solution here is to have a set of interfaces that are implemented for each RDBMS flavor and specified via the config, but that will take quite a bit more effort.

**Comment by FaaPz** [comment]
Thanks @kwhat! I like your idea making Slim-PDO more extendable. The long term solution you're suggesting might be something more for a V2, but changing some members and functions to protected should do the job for now without breaking things indeed. :smile:

**Comment by kwhat** [comment]
Yah, thats what I figured.  I can put in a Pull Request at some point today.

**Comment by FaaPz** [comment]
Perfect! :ok_hand:
