### ISSUE TITLE
Order By clause may not apply to update or delete.

### ISSUE THREAD

**Issue by kwhat** [FaaPz/PDO#22]
Should order by clause be available in UPDATE or DELETE?  I noticed that its currently on the StatementContainer but it will not work on MsSQL for UPDATE and DELETE.  Not sure what other sql may expect.

**Comment by kwhat** [comment]
This is only partially true.  I am going to fork and start hacking on some changes stuff.

**Comment by FaaPz** [comment]
Hi @kwhat, since V5 (maybe even earlier) MySQL allows the ORDER BY clause in UPDATE and DELETE. So that's why I've put it in the `StatementContainer`.

I hadn't thought about any other RDBMSes back then... :sweat_smile:
