### ISSUE TITLE
statement->limit()

### ISSUE THREAD

**Issue by srgzah** [FaaPz/PDO#24]
Hi,

`$statement->limit($number, $offset);` not working properly.
In MySQL this expression has the format `[LIMIT [offset,] rows]`

You have mixed up the parameters.
`$this->limit = intval($number).' , '.intval($end);`

**Comment by FaaPz** [comment]
Thanks for mentioning! Just released **v1.9.6** (8dc5d55a84b3824e508f611b23b329ac1ec5d0b2) with the fix included... :sweat_smile:
