### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by salt-lick** [FaaPz/PDO#25]
Would it be possible to add the ability to execute raw SQL commands with this package?

**Comment by FaaPz** [comment]
Hi @salt-lick, that's already possible. :wink: Slim-PDO extends raw PDO, so you could do something like:

``` php
$dbc = new \Slim\PDO\Database($dsn, $usr, $pwd);

$query = $dbc->prepare("SELECT * FROM `users`");

$result = $query->execute();

try
{
  var_dump($result->fetchAll());
}
catch(\PDOException $e)
{
  exit($e->getMessage());
}
```

**Comment by salt-lick** [comment]
Thank you. It was a long night and things were just not clicking...
