### ISSUE TITLE
Creating WHERE clauses

### ISSUE THREAD

**Issue by srgzah** [FaaPz/PDO#28]
Hello,

How can I make a query like this
`SELECT * FROM table WHERE field1 = 1 AND field2 = 2 AND (field3 = 3 OR field4 = 4);`

Thanks.

**Comment by FaaPz** [comment]
Hi @srgzah, not yet. It's in the making for V2.

**Comment by srgzah** [comment]
Ok

**Comment by srgzah** [comment]
Hi Fabian,
Can I make a raw query? I can not understand how to do this with Slim-PDO.

**Comment by FaaPz** [comment]
Yes, it is! Take a look at issue #25 :wink:

**Comment by srgzah** [comment]
Cool, thanks.
