### ISSUE TITLE
setPlaceholders doesn't handle NULL values correctly

### ISSUE THREAD

**Issue by mikegioia** [FaaPz/PDO#3]
I'm attempting to insert a row that has NULL values in the data array coming in, like this:

```
$pdo->insert([ 'id', 'usr', 'pwd', 'name' ])
    ->into( 'users' )
    ->values([ 1234, 'your_username', 'your_password', NULL ])
    ->execute();
```

`setPlaceholders` looks like it passes a `sizeof($value)` argument to `setPlaceholder`, but if the value is `NULL` then this will send in `0` there. This produces a SQL string that throws an error:

```
INSERT INTO users ( id , usr , pwd , name ) VALUES ( ? , ? ,  , ? )
```

I feel like the expected behavior is to just add the ? regardless if the value has a size.

**Comment by FaaPz** [comment]
Own fix provided in #4 and used in **v1.8.1** (a0c263288ef3bb31601b1107313008577d4c8449)
