### ISSUE TITLE
Increase counter

### ISSUE THREAD

**Issue by srgzah** [FaaPz/PDO#31]
Hi,

How can I perform this query:
`UPDATE table SET count = count + 1 WHERE id = ?`

Thanks.

**Comment by FaaPz** [comment]
Hi @srgzah, you could perform your query using raw PDO, because Slim-PDO is merely a wrapper.

``` php
$slimPdo->query("UPDATE `table` SET `count` = `count` + 1 WHERE `id` = ?");
```

Good luck!
