### ISSUE TITLE
ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by dfelix** [FaaPz/PDO#32]
Hello everyone,

I'm having some issues to implement a "ON DUPLICATE KEY UPDATE" sentence using Slim-PDO.

Is it supported?
I tried to find in documentation but no luck. Also tried to improvise but no luck either.

Best regards,
DF

**Comment by FaaPz** [comment]
@dfelix Unfortunately that's not (yet) supported. I suggest performing a raw PDO query instead and I've added this implementation on the V2 Road Map (#27). :wink:
