### ISSUE TITLE
Get the PDO class/connection

### ISSUE THREAD

**Issue by francoism90** [FaaPz/PDO#37]
Although Slim-PDO has almost every wanted feature, it doesn't cover all the MySQL (or other DB's) features. Is it possible to call the main \PDO class when needed?

Thanks. :)

**Comment by FaaPz** [comment]
Hi @francoism90, the `Database` class extends directly from `\PDO`, so you can use all the familiar methods and features whenever you feel like it. Slim-PDO doesn't overwrite any of those methods. 😉

**Comment by francoism90** [comment]
Oh that's great!  :)
Thanks for the reply.
