### ISSUE TITLE
Add Fulltext support

### ISSUE THREAD

**Issue by francoism90** [FaaPz/PDO#38]
Would be a cool additional feature. :)
See http://www.hackingwithphp.com/9/3/18/advanced-text-searching-using-full-text-indexes

```
$this->pdo->select()
        ->form('books')
        ->match('book_title', '+PHP -SQL')
..
```

Same as: `SELECT * FROM books WHERE MATCH(book_title) AGAINST ('+PHP -SQL' IN BOOLEAN MODE);`
IN BOOLEAN MODE could be default, and disabled if needed.

Thanks, and please let me know if you need more info. :)

**Comment by plasid** [comment]
Accommodate all new feature requests and soon end up with another bloated framework like Doctrine and Propel.
@francoism90 MySql Fulltext search has many pitfalls and I would not suggest using it, there are better solutions - look at i.e. Elastic and Solr etc.

**Comment by francoism90** [comment]
@atlantic8-web Thanks, will take a look at the alternatives. :)
