### ISSUE TITLE
limit() clause does not work directly from form values

### ISSUE THREAD

**Issue by quan-na** [FaaPz/PDO#43]
Current limit() clause use is_int() to check params. I use $request->getParsedBody()['rowCount'] and it does not work. I then must cast it to int.

Please include this in limit() document in case someone has the same problem.

**Comment by FaaPz** [comment]
Thanks! I've implemented a small validation check in **v1.10.0** (1e1bb3e49406594b76f6b897a9fe92ef6fb7cff6). Now it throws an error if the parameter isn't casted as integer before passing on.

**Comment by quan-na** [comment]
thank you

**Comment by kbaryshnikov** [comment]
There's a regression here. Please see #48

**Comment by rrpadilla** [comment]
Why you do not use in src/PDO/Clause/LimitClause.php
public function limit($limit = 15, $offset = 0)
