### ISSUE TITLE
select count(*) ? 

### ISSUE THREAD

**Issue by Sh1n1x** [FaaPz/PDO#5]
Hi !

Thank you for you great PHP Class. But how can make a select count ?

Here is an sample with simple PDO 

$sql = "SELECT count(*) FROM `table` WHERE foo = bar"; 
$result = $con->prepare($sql); 
$result->execute(); 
$number_of_rows = $result->fetchColumn();

**Comment by FaaPz** [comment]
Hi @Sh1n1x, this would be the easiest solution:

``` php
$slimPdo->select(array('COUNT(*)'))->from('table')->where('foo', '=', 'bar');
```

And thank you for the compliment! :blush:
