### ISSUE TITLE
Error using LIMIT with mysql

### ISSUE THREAD

**Issue by fatcho** [FaaPz/PDO#50]
I get this error when using LIMIT with mysql DB

Fatal error: Expects parameters as integers in /home/public_html/api/vendor/slim/pdo/src/PDO/Clause/LimitClause.php on line 29

My code is below:
   $selectStatement = $pdo->select()
                               ->from('news')
                               ->limit(10);

**Comment by kbaryshnikov** [comment]
I've just got into the same issue, see my PR #48

**Comment by fatcho** [comment]
Using offset its working.
->limit(10,0);

**Comment by alaabataineh92** [comment]
The problem in StatementContainer.php

 public function limit($number, $offset = null)
    {
        $this->limitClause->limit($number, $offset);

```
    return $this;
}
```

Change to 

 public function limit($number, $offset = 0)
    {
        $this->limitClause->limit($number, $offset);

```
    return $this;
}
```

**Comment by MarcHagen** [comment]
@alaa92 that doesnt work, the there will always be a offset enters in the query.
And the fix of @kbaryshnikov does this to

`if ($offset >= 0)
{
    $this->limit = intval($offset) . ' , ' . intval($number);
}`

`LIMIT 0 OFFSET 1`

**Comment by FaaPz** [comment]
Fixed with merge #62. New release coming soon.
