### ISSUE TITLE
Update table with existing value?

### ISSUE THREAD

**Issue by bduman** [FaaPz/PDO#63]
I looked set method of Slim\PDO\Statement\UpdateStatement class and it doesnt provide self column aritmetic operations such as `count=count+?`, `count=count-?` etc.  It could be flexible implement of this method with 2d arrays.

Thnx for repo.

**Comment by You2s** [comment]
I confirm, this feature would be very useful

**Comment by kwhat** [comment]
This is a duplicate of #108
