### ISSUE TITLE
get real sql from statement

### ISSUE THREAD

**Issue by StephanKrauss** [FaaPz/PDO#65]
Hello,

is there a way to get the real sql from the statement.

For example:

----------------------
 $selectStm = $slimPdo
                ->select()
                ->from('users')
                ->where('id','=',$id);

            $stm = $selectStm->execute();
            $data = $stm->fetchAll();

>> $mySql = $selectStm->getSql();
--------------------------

Your sincerly

Stephan

**Comment by belavina** [comment]
You can try `$stm->debugDumpParams();`
 ([documentation](http://php.net/manual/en/pdostatement.debugdumpparams.php))

**Comment by kwhat** [comment]
With version 2.x, you can simply call __toString() on any of the query objects to get their SQL representation.   For example:

```
$selectStm = $slimPdo
    ->select()
    ->from('users')
    ->where('id','=',$id);

$selectStm->__toString();
```

Please note that you cannot get the rendered SQL with the parameters escaped in the query.  This takes a lot of work to render and there is no out of the box solution from Zend.
