### ISSUE TITLE
Join not working with where

### ISSUE THREAD

**Issue by nidhi0801** [FaaPz/PDO#67]
Hi,

My query is  

$resultObj = $this->db->select()->from('shuttles')
            ->leftJoin('routes', 'routes.id', '=', 'shuttles.route_id')
            ->leftJoin('schedules', 'schedules.id', '=', 'shuttles.schedule_id')
            ->where('shuttles.id', '=', '4')
            ->where('shuttles.status','=','active')->execute();

        $result = $resultObj->fetchAll();

[Uploading whirlpool_mobility_qa3-29 PMtest.txt…](SQL export of tables)

its not returning me data for shuttle id =4.

Join not working with where conditions.
Can you please let me know the solution for the same

**Comment by dfelix** [comment]
->whereMany(array('shuttles.id'' => 4, 'shuttles.status' => 'active'), '=');

**Comment by kwhat** [comment]
1.x is not seeing much activity at the moment, please look into upgrading to v2.
