### ISSUE TITLE
Update date and add days

### ISSUE THREAD

**Issue by nalcantar** [FaaPz/PDO#70]
I would like to know how can i update the existing date and add some days to it. 
Example. update( ['date' => "DATE_ADD('date' , INTERVAL 2 DAY)" ] ).

Or how can i add a native sentence in the update function like SET date = "DATE_ADD('date' , INTERVAL 2 DAY)". 

Thanks in advance

**Comment by mattiasghodsian** [comment]
$oldDate = ""; // get from db or something
$newDate = date('Y-m-d', strtotime($oldDate. ' + 2 days'));

update( array('date' => $newDate) )->table('table')->where('id', '=', 1);

Maybe something like this, Not tested!!!

**Comment by kwhat** [comment]
This was recently added to the 2.x branch.   Please use the Raw clause class.  Ex:

`update( ['date' => new Raw("DATE_ADD('date' , INTERVAL 2 DAY)") ] )`
