### ISSUE TITLE
Offset is not options as per documentation

### ISSUE THREAD

**Issue by umakantp** [FaaPz/PDO#71]
Hi,

As per documentation, we can use 
```
// ... LIMIT 10
$statement->limit(10);
```
But if you go to LimitClause.php file, there is check "if (!is_int($number) || !is_int($offset)) {" which throws error if we do not pass 2nd argument. :-1: 

And btw event I pass both the arguments, there is not result. Please fix this.

**Comment by kwhat** [comment]
This has been resolved in 2.x, I don't know who is going to go back and fix the legacy stuff yet, if anyone.  I would highly recommend moving to the 2.x branch.
