### ISSUE TITLE
Insert or Update

### ISSUE THREAD

**Issue by StephanKrauss** [FaaPz/PDO#72]
Hello,

I'm looking for a way to write a combined update.
Example:

INSERT INTO table (a,b,c) VALUES (1,2,3),(4,5,6)
  ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);

Your sincerly

Stephan

**Comment by shaq147** [comment]
@StephanKrauss  Hi, I've implemented this functionality. You've just gotta add a few new functions to the InsertStatement.php file. See https://github.com/FaaPz/Slim-PDO/issues/86

**Comment by kwhat** [comment]
This is a duplicate of #86
