### ISSUE TITLE
funcion support for where clauses

### ISSUE THREAD

**Issue by psukys** [FaaPz/PDO#83]
So far, what I've looked into, there's not direct way of running functions, like
`find_in_set(:val, `column`)`

**Comment by kwhat** [comment]
Hi Psukys,

I have added support for internal methods and stored procedures to the 2.x-dev branch via the [Method](https://github.com/FaaPz/PDO/blob/2.x/src/Clause/Method.php) clause.  Let me know if this solves your issue.
