### ISSUE TITLE
Raw Query ?

### ISSUE THREAD

**Issue by im-madman** [FaaPz/PDO#85]
Is there any way to write raw query ? This feature is needed for some complex queries

**Comment by lhsazevedo** [comment]
Yes, its built on top of PDO and you can still use funcions like prepare(), bindParam(), execute () and so on.

**Comment by shaq147** [comment]
@im-madman An example is always nicer. Here's one I needed to do for an unsupported functionality (getting all column data from a table):

```
$db = new \Slim\PDO\Database($dsn, $usr, $pwd);
$stmt = $db->query('SHOW COLUMNS FROM table_name')
$stmt->execute();
$columns = $stmt->fetchAll();
```
