### ISSUE TITLE
TRUNCATE & DROP TABLE

### ISSUE THREAD

**Issue by dotmra** [FaaPz/PDO#97]
Hello,

Is there a method to truncate or drop a table using SlimPDO?
Something like `$db->truncate(TABLE)` or `$db->drop(TABLE)`?

**Comment by kwhat** [comment]
Not yet, but it maybe useful.  It also begs the question, should create table be supported?  There is quite a bit of complicity with create.

**Comment by dotmra** [comment]
Its okay.
I made the TRUNCATE function myself, directly in the code. (I know, I should have forked the project and then done a PR).
But at the time, I needed a fast solution, so decided to make it directly in the project.

It took less than 5 min to do so.
- But looking forward to TRUNCATE & DROP being a part of the wrapper.

And yes, there is quite a bit of complivity with create.
(That I can't make, but if it becomes a part of the wrapper, I'd love to see how it gets done) :)

**Comment by dotmra** [comment]
PR #113
